### ISSUE TITLE
nb端无法接收到q群或者q私聊信息

### ISSUE THREAD

**Issue by Agnes4m** [nonebot/adapter-qq#111]
## 环境
ubuntu == 22.04
python == 3.10.12,
nb-cli ==1.4.1
nonebot2 == 2.3.1
通过nb adapter方式安装本插件
nonebot-adapter-qq == 1.4.4

## 问题/步骤
在q.qq.com新建机器人，确定全局权限，沙盒模式和非沙盒模式都试过；
nonebot端正常设置env，图如下，在启动nb的时候也输出了正确连接到的log，但是群里艾特的信息和私聊信息均没有在nonebot端收到，但是qq频道的测试频道是正常收发信息的。

![image](https://github.com/nonebot/adapter-qq/assets/70925546/3ccb079a-ca56-4888-a445-baee1b36ec61)

## env
![image](https://github.com/nonebot/adapter-qq/assets/70925546/d1bcb88b-a4c9-4bc6-9ca2-cf35f6b502d3)

**Comment by yanyongyu** [comment]
群at消息和QQ私聊消息需要开启 `c2c_group_at_messages` intent，这个intent需要你有企业资质才可以使用

**Comment by Agnes4m** [comment]
感谢，已正常使用，建议在readme中说明各个参数的意思，增加可读性

**Comment by yanyongyu** [comment]
> 感谢，已正常使用，建议在readme中说明各个参数的意思，增加可读性

这些参数均在qq机器人官方文档中有说明
