### ISSUE TITLE
无法发送表情消息

### ISSUE THREAD

**Issue by gaodeng520** [nonebot/adapter-qq#113]
私域机器人，频道用echo可输出表情
但在群里的回复就是@夜笙等不到晚安 &lt;faceType=1,faceId="338",ext="eyJ0ZXh0Ijoi5oiR5oOz5byA5LqGIn0="&gt;&lt;faceType=1,faceId="338",ext="eyJ0ZXh0Ijoi5oiR5oOz5byA5LqGIn0="&gt;&lt;faceType=1,faceId="338",ext="eyJ0ZXh0Ijoi5oiR5oOz5byA5LqGIn0="&gt;
@夜笙等不到晚安 &lt;faceType=1,faceId="337",ext="eyJ0ZXh0Ijoi6Iqx5py16IS4In0="&gt;
类似于这种的了

**Comment by yanyongyu** [comment]
这问题你应该问QQ，文档写了还不支持
