### ISSUE TITLE
Feature: 添加可用于回复的 event id

### ISSUE THREAD

**Issue by Decrabbityyy** [nonebot/adapter-qq#119]
https://github.com/nonebot/adapter-qq/blob/afed4ce1aa8c4ee524341f8687f1e9a03c8bfedc/nonebot/adapters/qq/adapter.py#L340
希望能提供方法获取位于此处的payload 

原因：
https://bot.q.qq.com/wiki/develop/api-v2/server-inter/message/trans/msg-btn.html#%E7%82%B9%E5%87%BB%E5%9B%9E%E8%B0%83%E6%8C%89%E9%92%AE
该事件能够用于回复被动消息的id位于opcode同级。目前的InteractionCreateEvent事件无法获取到该id用于回复被动消息

**Comment by yanyongyu** [comment]
他不是和opcode同级吧，这个就是 `event.id`。

**Comment by Decrabbityyy** [comment]
> 他不是和opcode同级吧，这个就是 `event.id`。
能够用来被动的有个前缀INTERACTION_CREATE:

**Comment by yanyongyu** [comment]
根据文档 opcode 层级不应该有任何数据信息：

```json
{
  "op": 0,
  "d": {},
  "s": 42,
  "t": "GATEWAY_EVENT_NAME"
}
```

数据应该都在 data 字段内，且文档给出的[说明与示例](https://bot.q.qq.com/wiki/develop/api-v2/server-inter/message/trans/msg-btn.html#%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84%E4%B8%8E%E5%8D%8F%E8%AE%AE:~:text=string-,%E5%B9%B3%E5%8F%B0%E6%96%B9%E4%BA%8B%E4%BB%B6%20ID%EF%BC%8C%E5%8F%AF%E4%BB%A5%E7%94%A8%E4%BA%8E%E8%A2%AB%E5%8A%A8%E6%B6%88%E6%81%AF%E5%8F%91%E9%80%81,-type)表示应该使用 data 内的 id 进行回复，如果你觉得这个有问题请提供详细的数据内容，并向 QQ 反馈。

**Comment by Decrabbityyy** [comment]
了解

**Comment by yanyongyu** [comment]
根据群友反馈，可以使用event里的event_id，你可以看下上报的原始事件内容里有没有，如果有的话可以在event里加上这个字段。

**Comment by Decrabbityyy** [comment]
并没有这个字段
![image](https://github.com/user-attachments/assets/c545391c-adaa-4a42-be06-4bdbd460e85a)
