### ISSUE TITLE
WebSocket 连接异常断开

### ISSUE THREAD

**Issue by sxyubai** [nonebot/adapter-qq#121]
如图，网络错误，发生在官方bot提审期间，平时都没有任何问题，沙箱模式并未开启，没有挂服务器，是本地电脑，在夜间电脑息屏期间发生了两次，白天再次提审的时候又发生了一次（这次没有息屏并且我一直在旁边看着）
![3BAA4315DAC478668EBB903056D4F032](https://github.com/user-attachments/assets/5661799a-81c3-4759-966c-3c4791371613)

**Comment by yanyongyu** [comment]
这报错通常都是服务端断开连接，或者由你的代理产生（如果有的话）

**Comment by yanyongyu** [comment]
目前观察到可能断连的原因有 4009 session timed out，这是由于 QQ 服务端踢下线重连。但是看上去和你的报错也不一致。如果还有问题的话，欢迎 reopen
