### ISSUE TITLE
qq群markdown消息发送失败

### ISSUE THREAD

**Issue by huaimogu** [nonebot/adapter-qq#123]
报错如下
![image](https://github.com/user-attachments/assets/70132493-6e52-424a-b9c8-154ba8e8d083)
代码如下
![image](https://github.com/user-attachments/assets/c5853967-44e8-4d1b-8fe8-3a30226e6da2)
qq配置了markdown
![image](https://github.com/user-attachments/assets/1954e8de-7480-45cc-881f-d8520dfbcc7c)

**Comment by yanyongyu** [comment]
回复消息使用markdown需要DAU 2000+ 并在开放平台开通。默认只有主动消息可以使用 markdown。
