### ISSUE TITLE
是否可以支持在群聊内获取用户的频道id?

### ISSUE THREAD

**Issue by huanxin996** [nonebot/adapter-qq#133]
![Image](https://github.com/user-attachments/assets/ed8f1478-3477-4f09-b572-e916d3952659)
就像是这样，目前适配器可以支持吗

**Comment by lingdu2333** [comment]
这里的频道ID好像指的是用户的member_open_id 在其他项目（ 如![GSK](https://github.com/Hoshinonyaruko/Gensokyo) )好像确实可以获取
但是适配器好像确实无法获取到？

**Comment by yanyongyu** [comment]
那这个就是 `event.get_user_id()`

**Comment by lingdu2333** [comment]
![Image](https://github.com/user-attachments/assets/c60da3e0-ea1a-4ed8-ad5c-e5c11ee883d7)
目前适配器好像只支持user_openid（或者是member_openid？）
`event.get_user_id()`返回的依然是类似于`66C491DF4B45*****`等内容 并不是数字

但是官方返回的原始消息确实包含🤔

**Comment by yanyongyu** [comment]
那你可以从 `event.author.id` 获取老版本 id，由于该字段已经从文档删除且明确说明未来会移除，不建议使用。

**Comment by huanxin996** [comment]
测试群聊内
event.author.id和event.author.member_openid获取到的id仍是类似于* 66C491DF4B45*****的内容

**Comment by yanyongyu** [comment]
那就不存在你说的数字id，你说包含在原始消息里是哪里

**Comment by huanxin996** [comment]
了解了
