### ISSUE TITLE
Question: webhook 如何使用

### ISSUE THREAD

**Issue by 2-3-5-7** [nonebot/adapter-qq#136]
- 如果我要用 websocket 切换到 webhook 的话，除了 `"use_websocket": false` 以及开放平台上添加 webhook 地址，还需要配置什么吗？
- 这个 webhook 地址应该填服务器的 ip 后面要加什么呢？也就是 QQ开放平台上的“请求地址”应该填什么格式呢？
- 现在 webhook 方式开发完成了吗？我是否已经可以用了呢？

麻烦帮我解答一下，谢谢了

**Comment by yanyongyu** [comment]
目前webhook连接方式尚未发版，你着急的话可以使用master版本，如果遇到问题欢迎提交issue。请求地址填写：`https://ip:port/qq/webhook`

**Comment by 2-3-5-7** [comment]
不急的，那我等你开放好了，再看看

**Comment by yanyongyu** [comment]
目前是已经能够使用了，但是没有在实际环境测试过，你也可以试试

**Comment by mas-alone** [comment]
> 目前是已经能够使用了，但是没有在实际环境测试过，你也可以试试

请教大大，是在env里面填写port为开放平台允许的PORT = 8080
然后开放平台填写:
https://ip:8080/qq/webhook吗
我使用浏览器直接访问
http://ip:8080/qq/webhook的话会返回：
`
"detail": "Method Not Allowed"
`
换成https则无法访问：
`ERR_SSL_PROTOCOL_ERROR`

env里驱动器如下：
`DRIVER=~fastapi+~httpx`

是不是得配置支持https才可以，我看开放平台上前缀必须要https。
nb2带的uvicorn好像默认就是http
`12-10 12:30:51 [INFO] uvicorn | Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)`

**Comment by yanyongyu** [comment]
你可以自己搭一个nginx和证书做https转发，QQ必须要求https

**Comment by OverSky-gtq** [comment]
> 你可以自己搭一个nginx和证书做https转发，QQ必须要求https

自签名证书可以吗

**Comment by yanyongyu** [comment]
> 自签名证书可以吗

这你得问QQ，或者自己试下，应该可以
