### ISSUE TITLE
有没有其他的办法安装此adapter？

### ISSUE THREAD

**Issue by LsrlYrsc** [nonebot/adapter-qq#62]
在我的界面上，我只有QQ频道的选项，没有QQ的选项
nb adapter install qq(adapter-qq)下载的也是qqguild

**Comment by yanyongyu** [comment]
可能你的nbcli版本太低或者命中了尚未刷新缓存的cdn，你可以使用pip来安装然后自行添加到pyproject配置内

请在激活虚拟环境后执行以下命令：

```bash
pip install nonebot-adapter-qq
```
