### ISSUE TITLE
Vscode 调试启动与 Windows终端启动问题

### ISSUE THREAD

**Issue by Yuri-YuzuChaN** [nonebot/adapter-qq#69]
测试环境：Windows 11
Python版本：python 3.8 和 python 3.11

需要做插件测试如果用Vscode启动的话 `pydantic` 无法验证 `qq_bots` 这个值，如下图
![{835D3C9A-D84D-4567-8674-852A8FEF0892}](https://github.com/nonebot/adapter-qq/assets/65105396/282a0740-462a-42ee-a11d-aff1fb794133)

但是用windows终端启动的话是一切正常的
![{508420B5-AFF6-43b9-8BFE-3C449608E43A}](https://github.com/nonebot/adapter-qq/assets/65105396/8fef7a11-cfb8-43d0-b8a4-54826f520ff9)

是否可以验证一下，虽然是个小问题

**Comment by yanyongyu** [comment]
请配置你的vscode设置`python.envFile: ""`

**Comment by Yuri-YuzuChaN** [comment]
你好，这个问题依旧存在，`python.envFile` 默认值是可以访问到 `.env` 文件的，并且修改为绝对路径也依旧无法验证该值，但如果只是把 `QQ_BOTS` 去除是没有问题的

- 默认值
![image](https://github.com/nonebot/adapter-qq/assets/65105396/12e54cef-bccb-4c58-ad2d-37cf4ee00979)
- 绝对路径，正反斜杠均已尝试
![image](https://github.com/nonebot/adapter-qq/assets/65105396/b93fe76e-3770-4620-8570-232a5c336f0e)
- 去除 `QQ_BOTS` 
![image](https://github.com/nonebot/adapter-qq/assets/65105396/3648d523-ee2d-47e5-b314-11fce8620072)

**Comment by yanyongyu** [comment]
我是让你把python.envFile置空，阻止插件访问.env文件，因为插件会错误读取多行dotenv

**Comment by Yuri-YuzuChaN** [comment]
好的，谢谢
