### ISSUE TITLE
Bug: ws 断开连接时 bot 不存在

### ISSUE THREAD

**Issue by KarisAya** [nonebot/adapter-qq#73]
![{79EA1FAC-4364-4d5b-BAC0-D5FF6AB7E5BF}](https://github.com/nonebot/adapter-qq/assets/51886078/94062f87-4c30-4fd3-9498-a303cf96a1f1)
![{38676FB9-CE69-417d-9026-B6AAAFA80C08}](https://github.com/nonebot/adapter-qq/assets/51886078/4f047e91-29dd-406d-afe5-030d2055f734)

**Comment by yanyongyu** [comment]
断线的处理有一点小问题，暂时不影响使用，你这里断线的问题应该是你没有权限使用群bot
