### ISSUE TITLE
Bug: 群消息无法获取消息中@他人的信息

### ISSUE THREAD

**Issue by benx1n** [nonebot/adapter-qq#76]
![2 Y %W2{PY9SH1C%TVR%D_3](https://github.com/nonebot/adapter-qq/assets/48101337/b5761498-1a36-4ebc-9e97-827b800f7e48)
打印了一下MessageEvent，似乎拿不到文本中含有的@信息
在频道那边的官方sdk中@信息会被处理为`<@!(\d+)>`，不知道这是否是QQ群的问题？

**Comment by yanyongyu** [comment]
你可以配置日志等级为TRACE查看QQ下发的原始事件内容 来确认是否包含这一部分信息，看上去可能是QQ没给

**Comment by benx1n** [comment]
看了一下原始内容里也没有带@的信息，应该是QQ没给
