### ISSUE TITLE
建议火速适配最新群发富媒体消息api端点

### ISSUE THREAD

**Issue by HOursH** [nonebot/adapter-qq#83]
关于【机器人发送图片失败】问题处理情况说明
尊敬的各位参赛开发者们：
关于富媒体消息接口更新导致机器人发送图片失败的问题，目前平台已修复。其中主要有以下两个接口更新点需要大家重点关注：
1）两个发消息接口
/v2/groups/{group_openid}/messages，/v2/users/{openid}/messages 
新增 msg_type = 7 类型，用作发送富媒体消息，新增 media 字段作为发送内容参数，可结合 msg_id 和 msg_seq 字段使用被动消息的能力。
<img width="800" alt="8279ca053fc7b292c823cce381416a24" src="https://github.com/nonebot/adapter-qq/assets/100416394/47e9282e-54e5-4110-9979-6de9c2ed2939">

2) 两个富媒体消息接口
/v2/users/{openid}/files，/v2/groups/{group_openid}/files
更新使用协议机制
当请求参数字段 srv_send_msg 设置为 true，会当作【主动消息】直接发送到对应场景，超频会发送失败{"message":"msg limit exceed","code":22009}，
设置成 false 时，请求返回数据用作上述 media 字段作为入参参数内容，开发者可选择使用主动或被动的方式发送到具体的用户或群。
<img width="800" alt="03e4aafe2895ad2d5791ccc1cba779d8" src="https://github.com/nonebot/adapter-qq/assets/100416394/b66ae1d3-de87-4637-9e87-1451c5d9ecb7">

另外如遇其它问题，也欢迎大家联系我们反馈，给大家造成的不便，敬请谅解。目前大赛期间，问题咨询及反馈相对较多，希望大家多多理解，耐心等待。
@全体成员

**Comment by yanyongyu** [comment]
我知道你很急，但是你先别急

**Comment by HOursH** [comment]
> 我知道你很急，但是你先别急

急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急急
