### ISSUE TITLE
频道发送markdown消息报错

### ISSUE THREAD

**Issue by liu-zhou-L** [nonebot/adapter-qq#96]
频道发送markdown消息时，会出现错误如下
`nonebot.adapters.qq.exception.ActionFailed: <ActionFailed: 500, code=304041, message=reply messageg not allow markdown, trace_id=xxxxx>`
频道应该发送md消息时不为reply

**Comment by yanyongyu** [comment]
发送消息时不要携带message reference

**Comment by yanyongyu** [comment]
QQ群目前无法获取任何除了文本以外的信息
