### ISSUE TITLE
适配器每30min自动重连

### ISSUE THREAD

**Issue by Cypas** [nonebot/adapter-qq#97]
![image](https://github.com/nonebot/adapter-qq/assets/53274578/97c21dda-0d59-4f56-854e-57c0c8dce9ac)
![image](https://github.com/nonebot/adapter-qq/assets/53274578/cff5c18b-bb20-4b81-9c4c-b320095d8cb7)
适配器每30min都会自动断开连接并进行重连，会影响正在处理的matcher，与腾讯服务器的ws自动重连可否在适配器内部完成

**Comment by yanyongyu** [comment]
重连事件由腾讯方发出，适配器在收到事件的时候进行重连，重连期间bot不可用，请自行处理
